// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpBGaksTIUacoFXIyXbk4hBr21Tvmx2xM',
    appId: '1:103978403761:web:df5e2947f8034dae5a1f90',
    messagingSenderId: '103978403761',
    projectId: 'noteable-e087f',
    authDomain: 'noteable-e087f.firebaseapp.com',
    storageBucket: 'noteable-e087f.firebasestorage.app',
    measurementId: 'G-RTTNJ81KH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxSUI_sryPjbgtVipVdco5gCgrjXItsM',
    appId: '1:103978403761:android:feae9077f3ab5fcd5a1f90',
    messagingSenderId: '103978403761',
    projectId: 'noteable-e087f',
    storageBucket: 'noteable-e087f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVE4eAjH4fORextlRXyssYJ4ysHuuUpZw',
    appId: '1:103978403761:ios:6780aea1a1cccf105a1f90',
    messagingSenderId: '103978403761',
    projectId: 'noteable-e087f',
    storageBucket: 'noteable-e087f.firebasestorage.app',
    iosClientId: '103978403761-ejgfbeda55lnj04m5j3dkbbh23n9pdnq.apps.googleusercontent.com',
    iosBundleId: 'com.zelo.zelo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVE4eAjH4fORextlRXyssYJ4ysHuuUpZw',
    appId: '1:103978403761:ios:6780aea1a1cccf105a1f90',
    messagingSenderId: '103978403761',
    projectId: 'noteable-e087f',
    storageBucket: 'noteable-e087f.firebasestorage.app',
    iosClientId: '103978403761-ejgfbeda55lnj04m5j3dkbbh23n9pdnq.apps.googleusercontent.com',
    iosBundleId: 'com.zelo.zelo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpBGaksTIUacoFXIyXbk4hBr21Tvmx2xM',
    appId: '1:103978403761:web:5a58f7c5a1d888195a1f90',
    messagingSenderId: '103978403761',
    projectId: 'noteable-e087f',
    authDomain: 'noteable-e087f.firebaseapp.com',
    storageBucket: 'noteable-e087f.firebasestorage.app',
    measurementId: 'G-RDM5YR3TQZ',
  );
}
